from convert_gangstr_spec_to_expansion_hunter_variant_catalog_modified import process_variant_catalog

process_variant_catalog("marshfield_regions_gangstr_untrimmed_coordinates.bed", "marshfield_regions_eh_untrimmed_coordinates.json")






