[associatr]
# egene file
egene = 'gs://cpg-bioheart-test/str/associatr/cond_analysis/input_files/egenes.csv'
# gs://... to the chr-specific output of qc_filters_associatr.py
vcf_file_dir='gs://cpg-bioheart-test/str/associatr/input_files/vcf/v1-chr-specific'
cis_window_dir='gs://cpg-bioheart-test/str/associatr/cond_analysis/bioheart_n990/input_files/cis_window_files/v1'
pheno_cov_numpy_dir='gs://cpg-bioheart-test/str/associatr/cond_analysis/bioheart_n990/input_files/pheno_cov_numpy/v1'
max_parallel_jobs=500
cis_window_size=100000
# version of the output
version='v1'
# job storage
job_storage = '0G'
job_cpu =1
always_run = false
