[associatr]
celltypes='CD4_TCM'
# gs://... to the chr-specific output of qc_filters_associatr.py
vcf_file_dir='gs://cpg-bioheart-test/str/associatr/input_files/vcf/v1-chr-specific'
pheno_cov_numpy_dir='gs://cpg-bioheart-test/str/associatr/input_files/240_libraries_tenk10kp1_v2/inflation_debug/pheno_cov_numpy/v1/1'
max_parallel_jobs=500
# version of the output
version='v1-genome-wide'
# job storage
job_storage = '40G'
job_cpu =2
