[associatr]
celltypes='CD4_TCM'
chromosomes='chr22'
# gs://... to the chr-specific output of qc_filters_associatr.py
# vcf_file_dir='gs://cpg-bioheart-test/str/associatr/input_files/vcf/v1-chr-specific'
vcf_file_dir='gs://cpg-bioheart-test/str/associatr/tob_freeze_1/bgzip_tabix/v4'
cis_window_dir='gs://cpg-bioheart-test/str/associatr/tob_n1055/input_files/cis_window_files/v1'
pheno_cov_numpy_dir='gs://cpg-bioheart-test/str/associatr/tob_n1055/input_files/pheno_cov_numpy/v1'
gene_list_dir ='gs://cpg-bioheart-test/str/associatr/tob_n1055/input_files/scRNA_gene_lists/1_min_pct_cells_expressed'
max_parallel_jobs=500
cis_window_size=100000
# version of the output
version='v1-nonlinear'
# job storage
job_storage = '0G'
job_cpu =1
always_run=false
