[get_cis_numpy]
# GCS directory to the input AnnData objects
input_h5ad_dir = 'gs://cpg-tenk10k-test/saige-qtl/300-libraries/anndata_objects_from_HPC'
# GCS directory to the input pseudobulk CSV files
input_pseudobulk_dir = 'gs://cpg-tenk10k-test/str/associatr/final-freeze/input_files/pseudobulk/tob_ids_n1055'
# GCS directory to the input covariate CSV files
input_cov_dir = 'gs://cpg-tenk10k-test/str/associatr/rna_calib/tob_n950/input_files/covariates/1_rna_pcs'
chromosomes = 'chr1'
cell_types = 'CD8_TEM'
# cis window size in bp
cis_window = 100000
version = 'v1'
job_cpu = 1
job_memory = 'standard'
job_storage = '0G'
# To avoid exceeding Google Cloud quotas, set a concurrency as a limit.
max_parallel_jobs = 500
# filter out genes that are expressed in fewer than XX% of cells
min_pct = 1
snp_vcf_dir = "None"
remove_samples_file= "None"