[get_cis_numpy]
# GCS directory to the input AnnData objects
input_h5ad_dir = 'gs://cpg-bioheart-test/tenk10k/str/saige-qtl/300-libraries/anndata_objects_from_HPC'
# GCS directory to the input pseudobulk CSV files
input_pseudobulk_dir = 'gs://cpg-tenk10k-test/sv/input_files/bioheart_n968/pseudobulk'
# GCS directory to the input covariate CSV files
input_cov_dir = 'gs://cpg-tenk10k-test/sv/input_files/bioheart_n968/covariates/10_rna_pcs'
chromosomes = 'chr1'
cell_types = 'CD8_TEM'
# cis window size in bp
cis_window = 1000000
version = 'v1'
job_cpu = 1
job_memory = 'standard'
job_storage = '0G'
# To avoid exceeding Google Cloud quotas, set a concurrency as a limit.
max_parallel_jobs = 500
# filter out genes that are expressed in fewer than XX% of cells
min_pct = 1
