[get_cis_numpy]
# GCS directory to the input AnnData objects
input_h5ad_dir = 'gs://cpg-bioheart-test/str/240_libraries_tenk10kp1_v2/cpg_anndata'
# GCS directory to the input pseudobulk CSV files
input_pseudobulk_dir = 'gs://cpg-bioheart-test/str/associatr/bioheart_n990/input_files/pseudobulk'
# GCS directory to the input covariate CSV files
input_cov_dir = 'gs://cpg-bioheart-test/str/associatr/bioheart_n990/input_files/covariates/7_rna_pcs'
chromosomes = 'chr19'
cell_types = 'B_naive'
# cis window size in bp
cis_window = 100000
version = 'v1-cond-analysis/chr19_48110531'
job_cpu = 2
job_memory = 'standard'
job_storage = '10G'
# To avoid exceeding Google Cloud quotas, set a concurrency as a limit.
max_parallel_jobs = 500
# filter out genes that are expressed in fewer than XX% of cells
min_pct = 1
# GCS path to the file containing the list of samples to remove
remove_samples_file = 'gs://cpg-bioheart-test/str/associatr/input_files/remove-samples.txt'
# SNP loci to condition on
#note chrom for snp loci is strictly numeric eg 20:...
# set snp_vcf_dir == 'gs//cpg-bioheart-test' if no SNP loci to condition on
snp_vcf_dir = 'gs://cpg-bioheart-test'
snp_loci=[]
# STR loci to condition on
# set str_vcf_dir == 'gs//cpg-bioheart-test' if no STR loci to condition on
str_vcf_dir = 'gs://cpg-bioheart-test/str/associatr/input_files/vcf/v1-chr-specific'
# note chrom for STR loci has the chr prefix
str_loci =['chr19:48110531']
str_motifs = ['GCTCCGGAATCCGGTGCGGAGGCTTGG']
