[associatr]
celltypes='B_intermediate'
chromosomes='chr6,chr5,chr4,chr3,chr2,chr1,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22'
# gs://... to the chr-specific output of qc_filters_associatr.py
vcf_file_dir='gs://cpg-tenk10k-test/str/associatr/final-freeze/input_files/tr_vcf/v1-chr-specific'
cis_window_dir='gs://cpg-tenk10k-test/str/cellstate/input_files/meanpool/stratified/tob/cis_window_files'
pheno_cov_numpy_dir='gs://cpg-tenk10k-test/str/cellstate/input_files/meanpool/stratified/tob/pheno_cov_numpy'
gene_list_dir ='gs://cpg-tenk10k-test/str/cellstate/input_files/meanpool/stratified/tob/scRNA_gene_lists/1_min_pct_cells_expressed'
max_parallel_jobs=500
cis_window_size=100000
pathway = 'GOBP_STEROID_HORMONE_MEDIATED_SIGNALING_PATHWAY_subtype'
# job storage
job_storage = '0G'
job_cpu =1
always_run=false
