[pseudobulk]
# GCS Path to the input AnnData object
input_dir = 'gs://cpg-tenk10k-test/str/saige-qtl/300-libraries/anndata_objects_from_HPC'
# GCS Path to the sample ID file to do the analysis o
sample_id_file_path = 'gs://cpg-bioheart-test/str/associatr/final-freeze/input_files/pseudobulk/helper/tob_ids_n1055.csv'
# name of the cell type, comma separated if multiple
cell_types ='B_intermediate'
# Chromosome number eg 1, comma separated if multiple
chromosomes ='1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22'
# Storage of the batch job eg 30G
job_storage = '8G'
# Memory of the batch job
job_memory = 'standard'
# Number of CPUs of Hail batch job
job_cpu = 4
# Target sum of counts per cell (for normalization purposes)
target_sum = 1e6
# Minimum percentage of cells expressing a gene to be included in the pseudobulk
min_pct = 1
#pathway GOBP as per gs://cpg-bioheart-test/str/trdeepid/bcells/pathway_attributions_sublabel.h5ad
#pathway = 'GOBP_STEROID_HORMONE_MEDIATED_SIGNALING_PATHWAY_subtype'
#pathway = 'GOBP_MULTI_MULTICELLULAR_ORGANISM_PROCESS_subtype'
pathway = 'GOBP_NATURAL_KILLER_CELL_ACTIVATION_subtype'