from convert_gangstr_spec_to_expansion_hunter_variant_catalog_modified_0_based import process_variant_catalog

process_variant_catalog("catalogs/marshfield_regions_gangstr_untrimmed_coordinates.bed", "catalogs/marshfield_regions_eh_trimmed_coordinates_0_based.json")





