[associatr]
pheno_cov_numpy_dir='gs://cpg-bioheart-test/str/associatr-atac/tob/input_files/10kb_estrs'
cell_types='B_naive,B_memory,CD4_CTL,CD4_TCM'
#CD8_TCM,cDC2,HSPC,NK_CD56bright,Plasmablast,B_intermediate,CD4_Naive,CD4_TEM,CD8_TEM,dnT,MAIT,NK_Proliferating,Treg,CD16_Mono,CD4_Proliferating,CD8_Naive, cDC1, gDT, NK,pDC'
vcf_dir='gs://cpg-bioheart-test/str/atac-seq/filtered_vcfs/estrs/v1-remove-rare-GTs/estrs'
max_parallel_jobs=1000
cis_window_size=10000
job_storage = '0G'
job_cpu =0.25
always_run=false