[associatr]
pheno_cov_numpy_dir='gs://cpg-bioheart-test/str/associatr-atac/tob/input_files/10kb_estrs'
cell_types= 'CD14_Mono'
vcf_dir='gs://cpg-bioheart-test/str/atac-seq/filtered_vcfs/estrs'
max_parallel_jobs=1000
cis_window_size=10000
job_storage = '0G'
job_cpu =0.25
always_run=false