[get_cis_numpy]
pseudobulk_dir = 'gs://cpg-bioheart-test/str/atac-seq'
loc_filtered_dir = 'gs://cpg-bioheart-test/str/atac-seq/fm-etrs/10kb-estrs-peaks/meta_fixed'
cell_types = 'NK_Proliferating,Plasmablast,Treg,cDC1'
#B_intermediate,B_naive,B_memory,ASDC,cDC2,dnT,gdT,pDC,CD14_Mono,CD16_Mono,CD4_CTL,CD4_Naive,CD4_Proliferating,CD4_TCM,CD4_TEM,CD8_Naive,CD8_TCM,CD8_TEM,HSPC,MAIT,NK,NK_CD56bright
#,,,,NK_Proliferating,Plasmablast,Treg,cDC1
covariate_path = 'gs://cpg-bioheart-test//str/associatr/final-freeze/input_files/tob_n950_sample_covariates.csv'
job_cpu = 0.25
job_memory = 'standard'
job_storage = '0G'
# To avoid exceeding Google Cloud quotas, set a concurrency as a limit.
max_parallel_jobs = 500