---
title: "trf_output"
author: "Hope"
date: "15/02/2023"
output: html_document
---

```{r}
library('rjson')
library('spgs')
library(readxl)
library(tidyverse)
```

```{r}
#reads in dictionary value of locusName: TRF motif metrics output
trf_output = fromJSON(file = "2. TRF_find_motif/filtered_trf_output_modified.txt") %>% as.data.frame() %>% gather() 
trf_output = trf_output %>% mutate (key = case_when(key == "X16PTEL06"~ "16PTEL06",
                                       key == "X18QTEL11"~ "18QTEL11",
                                       key == "X2QTEL47" ~ "2QTEL47",
                                       key == "X4PTEL04"~ "4PTEL04",
                                       key == "MFD424.TTTA003"~ "MFD424-TTTA003",
                                       key == "MFD442.GTTT002" ~ "MFD442-GTTT002",
                                       key == "MFD455.AAT052"~"MFD455-AAT052",
                                       TRUE ~ key))
```
`

```{r}
#read in PCR sequences for each locus 
fasta = read_excel("1. UCSC_insilicoPCR/482_loci_with_primers_UCSC_remove_fix_alt.xlsx") %>% select(-...1)
fasta$coordinate = gsub("\r\n", " ", fasta$coordinate)
fasta$coordinate = str_trim(fasta$coordinate, side = "both")

#there's a random pattern of white space that separates the PCR sequence, so I had to separate everything and then recombine, probably a better way to do this! 
fasta = fasta %>% filter(coordinate != "no match")%>% separate(coordinate, c("coordinates", "PCR_length", "forward_primer", "reverse_primer", "PCR_sequence_1", "PCR_sequence_2", "PCR_sequence_3", "PCR_sequence_4", "PCR_sequence_5", "PCR_sequence_6", "PCR_sequence_7", "PCR_sequence_8"), sep = " ")

fasta = fasta %>% mutate(PCR_sequence_2 = replace_na(PCR_sequence_2, ""),
                  PCR_sequence_3 = replace_na(PCR_sequence_3, ""),
                  PCR_sequence_4 = replace_na(PCR_sequence_4, ""),
                  PCR_sequence_5 = replace_na(PCR_sequence_5, ""),
                  PCR_sequence_6 = replace_na(PCR_sequence_6, ""),
                  PCR_sequence_7 = replace_na(PCR_sequence_7, ""),
                  PCR_sequence_8 = replace_na(PCR_sequence_8, "")
  
)

fasta$PCR_sequence = paste(fasta$PCR_sequence_1, fasta$PCR_sequence_2, fasta$PCR_sequence_3, fasta$PCR_sequence_4, fasta$PCR_sequence_5, fasta$PCR_sequence_6, fasta$PCR_sequence_7, fasta$PCR_sequence_8)

fasta$PCR_sequence = gsub(" ", "", fasta$PCR_sequence)

#remove unnecc variables 
fasta = fasta %>% select(-PCR_sequence_1, -PCR_sequence_2, - PCR_sequence_3, -PCR_sequence_4, -PCR_sequence_5, -PCR_sequence_6, -PCR_sequence_7, -PCR_sequence_8, -forward_primer, -reverse_primer)

fasta$PCR_length = gsub("bp", "", fasta$PCR_length)
```

```{r}
#combine the PCR sequences with TRF output data
fasta = merge(trf_output, fasta, all.y = TRUE, by.x = "key", by.y = "alternateName")

#separate trf metrics output into various attributes 
fasta = fasta %>% separate(value, c("trf_start_index", "trf_end_index", "trf_period", "trf_num_repeats", "trf_size_consensus", "trf_percent_match", "trf_percent_indels", "trf_alignment", "trf_percent_composition_1", "trf_percent_composition_2", "trf_percent_composition_3", "trf_percent_composition_4", "trf_entropy", "trf_motif", "trf_repeat_sequence"), sep = " ")

#categorise TRF outputs based on sense of the strand 
fasta= fasta %>% mutate(sense = case_when(
  grepl("-", coordinates)~"antisense",
  grepl("+", coordinates)~ "sense",
  TRUE ~ "nosense"
))

#new variables start_coordinate_PCR and end_coordinate_PCR
fasta = fasta %>% separate(coordinates, c("chr", "coordinates"), sep = ":") %>% separate(coordinates, c("start_coordinate_PCR", "end_coordinate_PCR"), sep = "[+|-]") 

fasta$chr = gsub(">", "", fasta$chr)

fasta$trf_start_index = as.numeric(fasta$trf_start_index)
fasta$trf_end_index = as.numeric(fasta$trf_end_index)
fasta$end_coordinate_PCR = as.numeric(fasta$end_coordinate_PCR)
fasta$start_coordinate_PCR = as.numeric(fasta$start_coordinate_PCR)

#create new variables representing the catalog_start_coordinate and catalog_end_coordinate. catalog refers to the coordinates for the STR locus catalog. So the start and end coordinates should be the start and end of the STR regions 

fasta = fasta %>% mutate(catalog_start_coordinate_0_based = case_when(
  sense == "sense" ~ start_coordinate_PCR + trf_start_index-2, 
  sense== "antisense" ~ end_coordinate_PCR - trf_end_index
),
  catalog_end_coordinate = case_when(
sense == "sense"  ~start_coordinate_PCR + trf_end_index -1,
sense == "antisense" ~ end_coordinate_PCR - trf_start_index+1

  )
)

#STRs defined on antisense strands need a bit of extra work to polish. 

## found the reverse complement of the repeat_sequence identified by TRF for each STR defined on antisense strand 
fasta = fasta %>% mutate (trf_repeat_sequence = case_when(
                  sense == "antisense"~ reverseComplement(trf_repeat_sequence),
                  TRUE ~ trf_repeat_sequence)  
                  )

## Need to run TRF to redefine motifs on the antisense strand so --> creation of trf input

trf_input = fasta %>% filter(sense == "antisense") %>% select(chr,catalog_start_coordinate_0_based, catalog_end_coordinate, trf_repeat_sequence)

trf_input$name = paste(">",trf_input$chr,":" ,trf_input$catalog_start_coordinate_0_based, "-", trf_input$catalog_end_coordinate, sep = "")
trf_input = trf_input %>% select(name, trf_repeat_sequence)
write.table(trf_input, file = "trf_input_antisense.txt", sep = "\n", row.names = FALSE, quote = FALSE)

fasta = fasta %>% mutate(catalog_start_coordinate_1_based = catalog_start_coordinate_0_based+1)
```

```{r}
trf_output_antisense = read.csv("3. redefining_motifs_on_antisense/trf_output_antisense.txt") %>% separate(sequence, c("chr","coordinates" ), sep = ":") %>% separate(coordinates, c("catalog_start_coordinate_0_based", "catalog_end_coordinate"), sep = "-") %>% rename("updated_motif" = "motif")
```


```{r}
#Update fasta dataframe with redefined antisense motifs 
fasta = merge(fasta, trf_output_antisense, by = c("chr", "catalog_start_coordinate_0_based", "catalog_end_coordinate"), all.x = TRUE)
```

```{r}
fasta = fasta %>% mutate(trf_motif = case_when(sense == "antisense"~ updated_motif,
                                       TRUE ~trf_motif))
fasta = fasta %>% select(-updated_motif)

fasta %>% filter(sense == "antisense") %>% select(chr, catalog_start_coordinate_0_based, catalog_end_coordinate, trf_num_repeats, trf_motif, start_coordinate_PCR, end_coordinate_PCR)

```

```{r}
#gangstr catalog creation
#gangstr_catalog = fasta %>% select(chr,catalog_start_coordinate_1_based, catalog_end_coordinate, trf_motif) %>% mutate(motif_len= nchar(trf_motif)) %>% select(chr, catalog_start_coordinate_1_based, catalog_end_coordinate, motif_len, trf_motif)

#write.table(gangstr_catalog, file = "4. catalog_creation/catalogs/gangstr_catalog_hg38_backbone_1_based.bed", sep = "\t", row.names = FALSE, quote = FALSE)
```


```{r}
#hipstr catalog creation
#hipstr_catalog = fasta %>% select(chr,catalog_start_coordinate_1_based, catalog_end_coordinate, trf_period, trf_num_repeats, key) %>% mutate(trf_num_repeats = floor(as.numeric(trf_num_repeats)), catalog_end_coordinate = catalog_start_coordinate_1_based + as.numeric(trf_period)*trf_num_repeats-1) %>% select(chr, catalog_start_coordinate_1_based, catalog_end_coordinate, trf_period,trf_num_repeats, key)

#write.table(hipstr_catalog, file = "4. catalog_creation/catalogs/hipstr_catalog_hg38_backbone_trimmed_1_based.bed", sep = "\t", row.names = FALSE, quote = FALSE)
```


```{r}
##bed file for fermikit filtering

#fermikit_bed_1 = fasta %>% mutate(flank_1_f= start_coordinate_PCR-1, flank_1_r = catalog_start_coordinate_0_based-1) %>% select(chr, flank_1_f, flank_1_r) %>% filter(flank_1_f <=flank_1_r)

#fermikit_bed_2 = fasta %>% mutate(flank_1_f =catalog_end_coordinate+1, flank_1_r = end_coordinate_PCR) %>% select(chr, flank_1_f, flank_1_r)%>% filter(flank_1_f <=flank_1_r)

#write.table(rbind(fermikit_bed_1, fermikit_bed_2), file = "fermikit_upstream_downstream_regions_hg38_no_padding.bed", sep = "\t", row.names = FALSE, quote = FALSE)
```


```{r}
#generate hg19 input for fermikit intersection

#fermikit_liftover = read.table("6. Fermikit/fermikit_upstream_downstream_regions_hg38_no_padding_hg38_liftover_to_hg19.bed", header = F, sep = "\t")x
#fermikit_input_hg19 = fermikit_liftover %>% mutate(V1= gsub("chr","", V1)) %>% select(V1, V2, V3)
#write.table(fermikit_input_hg19, file = "fermikit_upstream_downstream_regions_no_padding_hg19.bed", sep = "\t", row.names = FALSE, quote = FALSE)
```


```{r}
fermikit_indels = read.table("6. Fermikit/263_all_samples_intersect_no_padding.vcf", sep = "\t", header = TRUE) %>% gather("sample_id", "gt", 10:272) %>% rename("start_coordinate_indel_hg19" = POS, "chr" = CHROM) %>% mutate(end_coordinate_indel_hg19 = start_coordinate_indel_hg19 +nchar(REF)-1,chr = paste("chr", chr, sep = "") ) %>% select(chr, start_coordinate_indel_hg19, end_coordinate_indel_hg19, sample_id, gt) 

#fermikit_indels %>% distinct(chr, start_coordinate_indel_hg19, end_coordinate_indel_hg19) %>% write.table(file = "6. Fermikit/fermikit_indel_coordinates_hg19_no_padding.bed", sep = "\t", row.names = FALSE, quote = FALSE) #note hg19 - must liftover back to hg38 to merge with the `fasta` dataframe 

fermikit_indels_hg38 = read.table("6. Fermikit/fermikit_indel_coordinates_hg19_liftover_to_hg38_no_padding.bed", sep = "\t", header = FALSE) %>% select(-V5)%>% rename("chr" = V1, "start_coordinate_indel_hg38" = V2, "end_coordinate_indel_hg38"= V3) %>% separate(V4, c("chr_hg19", "coordinates"), sep = ":") %>% separate(coordinates, c("start_coordinate_indel_hg19", "end_coordinate_indel_hg19"), sep = "-") %>% mutate(start_coordinate_indel_hg19 = as.numeric(start_coordinate_indel_hg19)-1) %>% distinct()

fermikit_indels_hg38 = merge(fermikit_indels, fermikit_indels_hg38, by= c("chr", "start_coordinate_indel_hg19", "end_coordinate_indel_hg19"))  %>% select(chr, start_coordinate_indel_hg38, end_coordinate_indel_hg38, sample_id,gt)

#fermikit_indels_hg38 %>% select(chr, start_coordinate_indel_hg38, end_coordinate_indel_hg38) %>% write.table(file = "6. Fermikit/fermikit_indel_coordinates_hg38_clean_no_padding.bed", sep = "\t", row.names = FALSE, quote = FALSE) 

#fasta %>% select(chr, start_coordinate_PCR, end_coordinate_PCR) %>% write.table(file = "6. Fermikit/fasta_pcr_coordinates.bed", sep = "\t", row.names = FALSE, quote = FALSE)

#bedtools intersect fasta_pcr_coordinates.bed with fermikit_indel_coordinates_hg38_clean.bed > output is fasta_intersect_no_padding.bed

indel_fasta_intersect = read.table("6. Fermikit/fasta_intersect_no_padding.bed", sep ="\t", header = FALSE) %>% select(-V4)%>% rename("chr" = V1,"start_coordinate_indel_hg38" = V2, "end_coordinate_indel_hg38" = V3, "start_coordinate_PCR" = V5, "end_coordinate_PCR" = V6) %>% distinct(chr, start_coordinate_indel_hg38, end_coordinate_indel_hg38, start_coordinate_PCR, end_coordinate_PCR)

fermikit_indels_hg38_clean = merge(fermikit_indels_hg38, indel_fasta_intersect, by = c("chr", "start_coordinate_indel_hg38", "end_coordinate_indel_hg38"), all.x = TRUE) %>% rename("indel_gt"= gt)%>% mutate(indel_gt = case_when (indel_gt == "0/0" ~0, TRUE ~ 1)) %>% group_by(sample_id, start_coordinate_PCR, end_coordinate_PCR) %>% summarise(indel_gt = sum(indel_gt)) %>% filter(!is.na(start_coordinate_PCR) & !is.na(end_coordinate_PCR)) %>% ungroup () 

sgdp_metadata = read.table("5. HGDP_SGDP_fermikit_sample_ids/SGDP_metadata.279public.21signedLetter.44Fan.samples.txt", header = TRUE, sep = "\t") %>% mutate(SGDP_ID=gsub("-", ".", SGDP_ID)) %>% select(SGDP_ID, Sample_ID)

fermikit_indels_hg38_clean = merge(fermikit_indels_hg38_clean, sgdp_metadata, by.x = "sample_id", by.y = "SGDP_ID",all.x = TRUE) %>% rename("hgdp_sample_id"= "Sample_ID")
```

```{r}
capillary_genotypes = read.csv("7. capillary_gt/capillary_genotypes_with_locusNames_rosenberg2005.csv") %>% select(-X,-locus_id, -population_id, - geographic_population, -predefined_region)

fasta_with_capillary = merge(fasta, capillary_genotypes, by.x = "key", by.y = "alternateName", all.y = TRUE) %>% rename("PCR_1" = genotype_1, "PCR_2" = genotype_2, "hgdp_sample_id" = "sample_id")

fasta_with_capillary$PCR_1 = na_if(fasta_with_capillary$PCR_1, -9)
fasta_with_capillary$PCR_2 = na_if(fasta_with_capillary$PCR_2, -9)
fasta_with_capillary$trf_num_repeats = as.numeric(fasta_with_capillary$trf_num_repeats)
fasta_with_capillary$PCR_length = as.numeric(fasta_with_capillary$PCR_length)

## working with fermikit calls
excluded_calls = merge(fasta_with_capillary, fermikit_indels_hg38_clean, by = c("hgdp_sample_id", "start_coordinate_PCR", "end_coordinate_PCR"))%>% filter(indel_gt!= 0|is.na(indel_gt)) 
```

```{r}
eh = read.csv("~/Downloads/str_410_sgdp_loci_data-frames_410_sgdp_loci_eh_debugged.csv") %>% select(sample_id, chr, start, end, e_allele_1, e_allele_2) %>% rename("catalog_start_coordinate_0_based" = start)


#%>% mutate(catalog_start_coordinate_0_based = as.numeric(catalog_start_coordinate_1_based)-1)

gangstr = read.delim("~/Downloads/str_410_sgdp_loci_data-frames_410_sgdp_loci_gangstr_debugged.tsv", sep = "\t") %>% select(sample_id, chr, start, g_allele_1, g_allele_2,g_q)%>% rename("catalog_start_coordinate_1_based" = start) %>% mutate(catalog_start_coordinate_0_based = as.numeric(catalog_start_coordinate_1_based)-1)

eh_gangstr = merge(eh, gangstr, by = c("sample_id", "chr", "catalog_start_coordinate_0_based"), all.x = TRUE) %>% rename("cpg_id"= "sample_id")

fasta_with_capillary_eh_gangstr = merge(eh_gangstr, fasta_with_capillary, by = c("cpg_id", "chr", "catalog_start_coordinate_0_based"), all.x = TRUE)

fasta_with_capillary_eh_gangstr = fasta_with_capillary_eh_gangstr %>% mutate(trf_num_repeats = (end -catalog_start_coordinate_0_based)/as.numeric(trf_period)) #makes it a whole number using the trimmed end coordinate 

fasta_with_capillary_eh_gangstr = anti_join(fasta_with_capillary_eh_gangstr, excluded_calls,by = c("cpg_id", "start_coordinate_PCR", "end_coordinate_PCR"))

fasta_with_capillary_eh_gangstr = fasta_with_capillary_eh_gangstr %>% filter(!key %in% c("AFM193xh4","AFM248vc5", "AFMb035xb9", "ATA092", "ATA67B07", "ATAA009", "GATA29A05", "GATA63B12", "GATA63F09", "GGAA17G05", "TTTA063", "ATA080", "ATA22G07", "ATA9B04", "ATGA020", "GATA178C11", "GATA31B11", "GATA46A12", "GATA63C02", "GGAA17G05", "SRA", "TCTA026", "2QTEL47")) #remove loci with fix_ or alt_ sequences in UCSC

```

```{r}
hipstr = read.csv("~/Downloads/str_410_sgdp_loci_data-frames_410_sgdp_loci_hipstr_debugged.csv")%>% separate(h_gb, c("h_gb_1", "h_gb_2"), sep = "\\|") %>% mutate(h_gb_1 = as.numeric(h_gb_1), h_gb_2 = as.numeric(h_gb_2))  %>% rename("key"= h_id,"hgdp_sample_id"= sample_id) %>% rename("end" = h_end, "chr" = h_chr)

mappings = read.table("~/Desktop/210_sample_mappings.txt", sep = ",") %>% rename("hgdp_sample_id" = V1, "cpg_id" = V2)

hipstr = merge(hipstr, mappings, by="hgdp_sample_id", all.x = TRUE)

fasta_with_capillary_eh_gangstr = merge(fasta_with_capillary_eh_gangstr, hipstr, by =c("cpg_id", "chr", "end"), all.x = TRUE)


fasta_with_capillary_eh_gangstr=fasta_with_capillary_eh_gangstr %>% mutate(h_allele_1 = trf_num_repeats +h_gb_1/h_period, h_allele_2 = trf_num_repeats +h_gb_2/h_period, h_alleles = round(h_allele_1) + round(h_allele_2), h_gbs = h_gb_1 + h_gb_2)



```

```{r}
fasta_with_capillary_eh_gangstr = fasta_with_capillary_eh_gangstr %>% mutate(capillary_allele_1 = (trf_num_repeats) + (PCR_1 -PCR_length)/nchar(trf_motif),
                               capillary_allele_2 = (trf_num_repeats) + (PCR_2 -PCR_length)/nchar(trf_motif) )

fasta_with_capillary_eh_gangstr = fasta_with_capillary_eh_gangstr %>% mutate(PCR_summed_diffs = PCR_1+PCR_2 -2*PCR_length)
fasta_with_capillary_eh_gangstr = fasta_with_capillary_eh_gangstr %>% mutate(PCR_diff_1 = PCR_1-PCR_length, PCR_diff_2 = PCR_2-PCR_length)

fasta_with_capillary_eh_gangstr = fasta_with_capillary_eh_gangstr %>% mutate(e_alleles = as.numeric(e_allele_1)+as.numeric(e_allele_2), 
                 g_alleles = as.numeric(g_allele_2)+as.numeric(g_allele_1),
                 capillary_alleles = floor(capillary_allele_1) + floor(capillary_allele_2)) #summed diploid genotypes 
```

```{r}
fasta_with_capillary_eh_gangstr =fasta_with_capillary_eh_gangstr %>% filter(!is.na(capillary_alleles))
fasta_with_capillary_eh_gangstr =fasta_with_capillary_eh_gangstr %>% filter(!is.na(h_alleles))
#fasta_with_capillary_eh_gangstr =fasta_with_capillary_eh_gangstr %>% filter(!grepl("_", nameInGenotypeDataFile))

fasta_with_capillary_eh_gangstr %>% filter(e_alleles == g_alleles) %>% count()/ (fasta_with_capillary_eh_gangstr %>% count())
fasta_with_capillary_eh_gangstr %>% filter(e_alleles == h_alleles) %>% count()/ (fasta_with_capillary_eh_gangstr %>% count())
fasta_with_capillary_eh_gangstr %>% filter(g_alleles == h_alleles) %>% count()/ (fasta_with_capillary_eh_gangstr %>% count())


(fasta_with_capillary_eh_gangstr %>% filter(e_alleles== capillary_alleles) %>%count())/ (fasta_with_capillary_eh_gangstr %>% count())

(fasta_with_capillary_eh_gangstr %>% filter((h_gbs-PCR_summed_diffs) ==0) %>%count())/ (fasta_with_capillary_eh_gangstr %>% count())
(fasta_with_capillary_eh_gangstr %>% filter(h_alleles== capillary_alleles) %>%count())/ (fasta_with_capillary_eh_gangstr %>% count())


(fasta_with_capillary_eh_gangstr %>% filter(g_alleles== capillary_alleles) %>%count())/ (fasta_with_capillary_eh_gangstr %>% count())

```


```{r}
library(ggbeeswarm)
library(ggforce)
my_vec = fasta_with_capillary_eh_gangstr %>% distinct(key.x)
my_vec = my_vec$key.x
split_keys = split(my_vec,             # Applying split() function
      ceiling(seq_along(my_vec) / 20))

fasta_with_capillary_eh_gangstr  %>% select(key.x,trf_period, e_alleles,g_alleles,h_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles, `HipSTR-capillary` = h_alleles-capillary_alleles) %>% gather(key = "caller_minus_capillary", value = "difference",7:9)  %>%filter(key.x %in% unlist(split_keys[6])) %>%ggplot(aes(x = key.x, y= difference, colour =caller_minus_capillary, alpha = 0.6,position = 'dodge' ))  +
geom_boxplot()+ theme_minimal()+ theme(panel.grid.minor = element_blank())+ xlab("locus")  +labs(color='Discrepancy') +ylab("Difference (num.repeats) from capillary")+ scale_y_continuous(breaks=seq(-15,0,1))

fasta_with_capillary_eh_gangstr %>% filter(key.x == "GAT004")

```

```{r}

##relative to ref num_repeats

library(ggbeeswarm)
library(ggforce)
reference_graph = fasta_with_capillary_eh_gangstr  %>% select(key.x, e_alleles,g_alleles,h_alleles,trf_num_repeats, capillary_alleles) %>% mutate(`EH-ref` = e_alleles-trf_num_repeats*2, `GangSTR-ref` = g_alleles-trf_num_repeats*2, `HipSTR-ref` = h_alleles-trf_num_repeats*2, `capillary-ref` = capillary_alleles-trf_num_repeats*2) %>% gather(key = "caller_minus_capillary", value = "difference",7:10) 

reference_graph$caller_minus_capillary = factor(reference_graph$caller_minus_capillary, levels = c("EH-ref", "GangSTR-ref", "HipSTR-ref", "capillary-ref"))

reference_graph%>%filter(key.x %in% unlist(split_keys[1])) %>%ggplot(aes(x = key.x, y= difference, colour =caller_minus_capillary, alpha = 0.6,position = 'dodge' ))  +
geom_boxplot()+ theme_minimal()+ theme(panel.grid.minor = element_blank())+ xlab("locus")  +labs(color='Discrepancy') +ylab("Difference (num.repeats) from reference")+ scale_y_continuous(breaks=seq(-15,10,1))

fasta_with_capillary_eh_gangstr %>% select(trf_num_repeats)

```

```{r}

# Create the function.
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
fasta_with_capillary_eh_gangstr_edited=fasta_with_capillary_eh_gangstr %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles,`HipSTR-capillary` = h_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(mode_EH_capillary = getmode(`EH-capillary`),mode_GangSTR_capillary = getmode(`GangSTR-capillary`), mode_HipSTR_capillary = getmode(`HipSTR-capillary`), median_EH_capillary = median(`EH-capillary`), median_GangSTR_capillary = median(`GangSTR-capillary`), median_HipSTR_capillary = median(`HipSTR-capillary`)) %>% ungroup() %>% mutate(is_mode_EH_capillary = case_when(mode_EH_capillary == `EH-capillary` ~ 1, TRUE ~0), is_mode_GangSTR_capillary = case_when(mode_GangSTR_capillary == `GangSTR-capillary` ~ 1, TRUE ~0), is_mode_HipSTR_capillary = case_when(mode_HipSTR_capillary == `HipSTR-capillary` ~ 1, TRUE ~0)) %>% group_by(key.x) %>% mutate(mode_EH_capillary_proportion = sum(is_mode_EH_capillary)/n(), mode_GangSTR_capillary_proportion = sum(is_mode_GangSTR_capillary)/n(),mode_HipSTR_capillary_proportion = sum(is_mode_HipSTR_capillary)/n())  %>%  mutate(capillary_alleles = case_when(mode_GangSTR_capillary==mode_EH_capillary & mode_EH_capillary == mode_HipSTR_capillary  & mode_EH_capillary_proportion >=0.5 &mode_HipSTR_capillary_proportion >=0.5 &mode_GangSTR_capillary_proportion >=0.5 &mode_GangSTR_capillary!=0 &mode_HipSTR_capillary == median_HipSTR_capillary & mode_EH_capillary == median_EH_capillary  ~ NA, TRUE ~ capillary_alleles))


fasta_with_capillary_eh_gangstr_edited=fasta_with_capillary_eh_gangstr_edited %>% filter(!is.na(capillary_alleles))


fasta_with_capillary_eh_gangstr_edited %>% filter(e_alleles == g_alleles) %>% nrow() / (fasta_with_capillary_eh_gangstr_edited %>%nrow())

fasta_with_capillary_eh_gangstr_edited %>% filter(e_alleles == h_alleles) %>% nrow()/ (fasta_with_capillary_eh_gangstr_edited %>% nrow())
fasta_with_capillary_eh_gangstr_edited %>% filter(g_alleles == h_alleles) %>% nrow()/ (fasta_with_capillary_eh_gangstr_edited %>% nrow())


(fasta_with_capillary_eh_gangstr_edited %>% filter(e_alleles== capillary_alleles) %>%nrow())/ (fasta_with_capillary_eh_gangstr_edited %>% nrow())

(fasta_with_capillary_eh_gangstr_edited %>% filter((h_gbs-PCR_summed_diffs) ==0) %>%nrow())/ (fasta_with_capillary_eh_gangstr_edited %>% nrow())

(fasta_with_capillary_eh_gangstr_edited %>% filter(h_alleles== capillary_alleles) %>%nrow())/ (fasta_with_capillary_eh_gangstr_edited %>% nrow())


(fasta_with_capillary_eh_gangstr_edited %>% filter(g_alleles== capillary_alleles) %>%nrow())/ (fasta_with_capillary_eh_gangstr_edited %>% nrow())

```

# Allele specific visualisation

```{r}
#the allele with the greater length will be max_allele, and the other allele will be min_allele
fasta_with_capillary_eh_gangstr_al = fasta_with_capillary_eh_gangstr
fasta_with_capillary_eh_gangstr_al$e_allele_1 = as.numeric(fasta_with_capillary_eh_gangstr_al$e_allele_1)
fasta_with_capillary_eh_gangstr_al$e_allele_2 = as.numeric(fasta_with_capillary_eh_gangstr_al$e_allele_2)
fasta_with_capillary_eh_gangstr_al$g_allele_1 = as.numeric(fasta_with_capillary_eh_gangstr_al$g_allele_1)
fasta_with_capillary_eh_gangstr_al$g_allele_2 = as.numeric(fasta_with_capillary_eh_gangstr_al$g_allele_2)

fasta_with_capillary_eh_gangstr_al$max_e_allele = apply(fasta_with_capillary_eh_gangstr_al[, 5:6 ], 1, max)
fasta_with_capillary_eh_gangstr_al$min_e_allele = apply(fasta_with_capillary_eh_gangstr_al[, 5:6 ], 1, min)

fasta_with_capillary_eh_gangstr_al$max_g_allele = apply(fasta_with_capillary_eh_gangstr_al[,8:9],1,max)
fasta_with_capillary_eh_gangstr_al$min_g_allele = apply(fasta_with_capillary_eh_gangstr_al[,8:9],1,min)

fasta_with_capillary_eh_gangstr_al$max_h_allele = apply(fasta_with_capillary_eh_gangstr_al[,51:52],1,max)
fasta_with_capillary_eh_gangstr_al$min_h_allele = apply(fasta_with_capillary_eh_gangstr_al[,51:52],1,min)

fasta_with_capillary_eh_gangstr_al$max_cap_allele = floor(apply(fasta_with_capillary_eh_gangstr_al[,55:56],1,max))
fasta_with_capillary_eh_gangstr_al$min_cap_allele = floor(apply(fasta_with_capillary_eh_gangstr_al[,55:56],1,min))

#create 2 variables storing the difference in alleles
fasta_with_capillary_eh_gangstr_al = fasta_with_capillary_eh_gangstr_al %>% mutate(
                              max_e_allele_diff = max_e_allele - max_cap_allele, 
                              min_e_allele_diff = min_e_allele - min_cap_allele,
                              max_g_allele_diff = max_g_allele - max_cap_allele, 
                              min_g_allele_diff = min_g_allele - min_cap_allele,
                              max_h_allele_diff = max_h_allele - max_cap_allele, 
                              min_h_allele_diff = min_h_allele - min_cap_allele,
                              )
fasta_with_capillary_eh_gangstr_al=fasta_with_capillary_eh_gangstr_al %>% gather(key = "caller_minus_capillary", value = "difference",71:76)

fasta_with_capillary_eh_gangstr_al%>%filter(key.x %in% unlist(split_keys[10])) %>%ggplot(aes(x = key.x, y= difference, colour =caller_minus_capillary, alpha = 0.6,position = 'dodge' ))  +
geom_boxplot()+ theme_minimal()+ theme(panel.grid.minor = element_blank())+ xlab("locus")  +labs(color='Discrepancy') +ylab("Difference (num.repeats) from capillary")+ scale_y_continuous(breaks=seq(-15,0,1))


split_keys
```
```{r}
fasta_with_capillary_eh_gangstr %>% filter(key.x == "GAT004")%>% select(e_alleles, capillary_alleles)
```
```{r}
fasta_with_capillary_eh_gangstr %>% filter(key.x == "GAT004") 

hipstr %>% filter(h_start == 216547254 & hgdp_sample_id == "LP6005441-DNA_H03")
```


```{r}

good_loci = fasta_with_capillary_eh_gangstr %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(mode_EH_capillary = getmode(`EH-capillary`),mode_GangSTR_capillary = getmode(`GangSTR-capillary`)) %>% ungroup() %>% mutate(is_mode_EH_capillary = case_when(mode_EH_capillary == `EH-capillary` ~ 1, TRUE ~0), is_mode_GangSTR_capillary = case_when(mode_GangSTR_capillary == `GangSTR-capillary` ~ 1, TRUE ~0)) %>% group_by(key.x) %>% mutate(mode_EH_capillary_proportion = sum(is_mode_EH_capillary)/n(), n= n(), mode_GangSTR_capillary_proportion = sum(is_mode_GangSTR_capillary)/n()) %>% mutate(capillary_alleles = case_when(mode_GangSTR_capillary==mode_EH_capillary & mode_EH_capillary_proportion >0.85 &mode_GangSTR_capillary_proportion >0.75 &mode_GangSTR_capillary==0 ~ NA, TRUE ~ capillary_alleles)) %>% filter(is.na(capillary_alleles))%>% select(nameInGenotypeDataFile) %>% distinct()

loci_with_systemic_shifts = fasta_with_capillary_eh_gangstr %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(mode_EH_capillary = getmode(`EH-capillary`),mode_GangSTR_capillary = getmode(`GangSTR-capillary`)) %>% ungroup() %>% mutate(is_mode_EH_capillary = case_when(mode_EH_capillary == `EH-capillary` ~ 1, TRUE ~0), is_mode_GangSTR_capillary = case_when(mode_GangSTR_capillary == `GangSTR-capillary` ~ 1, TRUE ~0)) %>% group_by(key.x) %>% mutate(mode_EH_capillary_proportion = sum(is_mode_EH_capillary)/n(), n= n(), mode_GangSTR_capillary_proportion = sum(is_mode_GangSTR_capillary)/n()) %>% mutate(capillary_alleles = case_when(mode_GangSTR_capillary==mode_EH_capillary & mode_EH_capillary_proportion >0.85 &mode_GangSTR_capillary_proportion >0.75 &mode_GangSTR_capillary!=0 ~ NA, TRUE ~ capillary_alleles)) %>% filter(is.na(capillary_alleles))%>% select(nameInGenotypeDataFile) %>% distinct()
```

# Misc analysis
```{r}
#comparing GC content in loci with good concordance with capillary vs systemic shifts

# good concordance 
fasta %>% mutate(num_g = str_count(trf_repeat_sequence, "g"), num_c = str_count(trf_repeat_sequence, "c"), gc_content = (num_g+num_c)/(str_length(trf_repeat_sequence))) %>% filter(key %in% good_loci$key.x) %>% summarise(mean_GC = mean(gc_content))

#sytemic shift loci 
fasta %>% mutate(num_g = str_count(trf_repeat_sequence, "g"), num_c = str_count(trf_repeat_sequence, "c"), gc_content = (num_g+num_c)/(str_length(trf_repeat_sequence))) %>% filter(key %in% loci_with_systemic_shifts$key.x) %>% summarise(mean_GC = mean(gc_content))

```
Good concordance loci have an average GC content that is half that of systemic shift loci 

```{r}
#Graph of GC content in PCR sequence 
gc_graph = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,h_alleles,capillary_alleles,PCR_sequence) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles, `HipSTR-capillary` = h_alleles-capillary_alleles,num_g = str_count(PCR_sequence, "g")+str_count(PCR_sequence, "G"), num_c = str_count(PCR_sequence, "c")+str_count(PCR_sequence, "C"), gc_content = (num_g+num_c)/(str_length(PCR_sequence))) 

gc_graph = gc_graph %>% mutate(gc_bin_tag = case_when( #creates bins for gangstr quality scores 
  gc_content <0.05 ~ '0-0.0.05',
  gc_content>=0.05 &gc_content<0.1 ~ '0.05-0.1', 
  gc_content>=0.1 &gc_content<0.15 ~ '0.1-0.15', 
  gc_content>=0.15 &gc_content<0.2 ~ '0.15-0.2', 
  gc_content>=0.2 &gc_content<0.25 ~ '0.2-0.25',
  gc_content>=0.25 &gc_content<0.3 ~ '0.25-0.3',
  gc_content>=0.3 &gc_content<0.35 ~ '0.3-0.35',
  gc_content>=0.35 &gc_content<0.4 ~'0.35-0.4',
  gc_content>=0.4 &gc_content<0.45 ~ '0.4-0.45',
  gc_content>=0.45 &gc_content<0.5 ~ '0.45-0.5',
  gc_content>=0.5 &gc_content<0.55 ~ '0.5-0.55',
  gc_content>=0.55 &gc_content<0.6 ~ '0.55-0.6',
  gc_content>=0.6&gc_content<0.7 ~'0.6-0.7',
  gc_content>=0.7 ~'>0.7'
))

gc_graph$gc_bin_tag = factor(gc_graph$gc_bin_tag, levels =c( '0-0.0.05',
'0.05-0.1', 
'0.1-0.15', 
 '0.15-0.2', 
 '0.2-0.25',
 '0.25-0.3',
 '0.3-0.35',
'0.35-0.4',
'0.4-0.45',
 '0.45-0.5',
'0.5-0.55',
'0.55-0.6','0.6-0.7','>0.7'))



gc_graph%>% gather(key = "caller_minus_capillary", value = "difference",7:9)  %>%ggplot(aes(x = gc_bin_tag, y= difference, colour =caller_minus_capillary, alpha = 0.6,position = 'dodge' ))  +
geom_boxplot()+ theme_minimal()+ theme(panel.grid.minor = element_blank())+ xlab("GC content of PCR sequence")  +labs(color='Discrepancy') +ylab("Difference (num.repeats) from capillary")+ scale_y_continuous(breaks=seq(-15,10,1))
```
```{r}

#Graph of GC content in TRF sequence 
gc_graph = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,h_alleles,capillary_alleles,trf_repeat_sequence) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles, `HipSTR-capillary` = h_alleles-capillary_alleles,num_g = str_count(trf_repeat_sequence, "g")+str_count(trf_repeat_sequence, "G"), num_c = str_count(trf_repeat_sequence, "c")+str_count(trf_repeat_sequence, "C"), gc_content = (num_g+num_c)/(str_length(trf_repeat_sequence)))%>% gather(key = "caller_minus_capillary", value = "difference",7:9)  

gc_graph = gc_graph %>% mutate(gc_bin_tag = case_when( #creates bins for gangstr quality scores 
  gc_content <0.05 ~ '0-0.0.05',
  gc_content>=0.05 &gc_content<0.1 ~ '0.05-0.1', 
  gc_content>=0.1 &gc_content<0.15 ~ '0.1-0.15', 
  gc_content>=0.15 &gc_content<0.2 ~ '0.15-0.2', 
  gc_content>=0.2 &gc_content<0.25 ~ '0.2-0.25',
  gc_content>=0.25 &gc_content<0.3 ~ '0.25-0.3',
  gc_content>=0.3 &gc_content<0.35 ~ '0.3-0.35',
  gc_content>=0.35 &gc_content<0.4 ~'0.35-0.4',
  gc_content>=0.4 &gc_content<0.45 ~ '0.4-0.45',
  gc_content>=0.45 &gc_content<0.5 ~ '0.45-0.5',
  gc_content>=0.5 &gc_content<0.55 ~ '0.5-0.55',
  gc_content>=0.55 &gc_content<0.6 ~ '0.55-0.6',
  gc_content>=0.6&gc_content<0.7 ~'0.6-0.7',
  gc_content>=0.7 ~'>0.7'
))

gc_graph$gc_bin_tag = factor(gc_graph$gc_bin_tag, levels =c( '0-0.0.05',
'0.05-0.1', 
'0.1-0.15', 
 '0.15-0.2', 
 '0.2-0.25',
 '0.25-0.3',
 '0.3-0.35',
'0.35-0.4',
'0.4-0.45',
 '0.45-0.5',
'0.5-0.55',
'0.55-0.6','0.6-0.7','>0.7'))


key_gc_content_asc = gc_graph %>% distinct(key.x, gc_content)%>% arrange(gc_content) %>% select(key.x)

key_gc_content_asc$key.x = factor(key_gc_content_asc$key.x, levels = key_gc_content_asc$key.x) 

split_keys_gc_content = split(key_gc_content_asc$key.x,             # Applying split() function
      ceiling(seq_along(key_gc_content_asc$key.x) / 50))

gc_graph%>% filter(gc_content == 0 & key.x %in% unlist(split_keys_gc_content[2]) )%>%ggplot(aes(x = key.x, y= difference, colour =caller_minus_capillary, alpha = 0.6,position = 'dodge' ))+ 
geom_boxplot()+ theme_minimal()+ theme(panel.grid.minor = element_blank())+ xlab("Loci with period ==4")  +labs(color='Discrepancy') +ylab("Difference (num.repeats) from capillary")+ scale_y_continuous(breaks=seq(-15,7,1))
```

```{r}
##Systemic shifts by motif 

motif_graph = fasta_with_capillary_eh_gangstr %>% select(trf_period, e_alleles,g_alleles,h_alleles,capillary_alleles, key.x) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles, `HipSTR-capillary` = h_alleles-capillary_alleles) %>% gather(key = "caller_minus_capillary", value = "difference",7:9) 


motif_graph%>%ggplot(aes(x = trf_period, y= difference, colour =caller_minus_capillary, alpha = 0.6,position = 'dodge' ))  +
geom_boxplot()+ theme_minimal()+ theme(panel.grid.minor = element_blank())+ xlab("Motif length")  +labs(color='Discrepancy') +ylab("Difference (num.repeats) from capillary")+ scale_y_continuous(breaks=seq(-15,0,1))


key_motif_len_asc = motif_graph %>% distinct(key.x, trf_period)%>% arrange(trf_period) %>% select(key.x)

key_motif_len_asc$key.x = factor(key_motif_len_asc$key.x, levels = key_motif_len_asc$key.x) 

split_keys_motif_len = split(key_motif_len_asc$key.x,             # Applying split() function
      ceiling(seq_along(key_motif_len_asc$key.x) / 50))


motif_graph%>% filter(trf_period ==4& key.x %in% unlist(split_keys_motif_len[5]) )%>%ggplot(aes(x = key.x, y= difference, colour =caller_minus_capillary, alpha = 0.6,position = 'dodge' ))+ 
geom_boxplot()+ theme_minimal()+ theme(panel.grid.minor = element_blank())+ xlab("Loci with period ==4")  +labs(color='Discrepancy') +ylab("Difference (num.repeats) from capillary")+ scale_y_continuous(breaks=seq(-15,7,1))

```

```{r}

#gencode work 

keys_minus_2 = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==-2) %>% distinct(key.x)


keys_minus_4 = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==-4) %>% distinct(key.x)

keys_minus_6 = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==-6) %>% distinct(key.x)

keys_minus_8 = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==-8) %>% distinct(key.x)
keys_minus_10 = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==-10) %>% distinct(key.x)
keys_minus_12 = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==-12) %>% distinct(key.x)
keys_plus_2= fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==2) %>% distinct(key.x)
keys_plus_4= fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==4) %>% distinct(key.x)



bad_keys = rbind(keys_minus_2, keys_minus_4, keys_minus_6, keys_minus_8, keys_minus_10, keys_minus_12, keys_plus_2, keys_plus_4)


keys_100_concord = fasta_with_capillary_eh_gangstr %>% select(key.x, e_alleles,g_alleles,capillary_alleles) %>% mutate(`EH-capillary` = e_alleles-capillary_alleles, `GangSTR-capillary` = g_alleles-capillary_alleles) %>% group_by(key.x) %>% mutate(max_EH_capillary = max(`EH-capillary`), min_EH_capillary = min(`EH-capillary`)) %>% filter(min_EH_capillary==max_EH_capillary & min_EH_capillary ==0) %>% distinct(key.x)
good_call_loci = fasta%>% filter(key %in% keys_100_concord$key.x)%>% select(chr, catalog_start_coordinate_0_based, catalog_end_coordinate)

#write.table(good_call_loci, file = "Rosenberg_good_loci_STR_catalog_coordinates.bed", sep = "\t", row.names = FALSE, quote = FALSE)

bad_call_loci = fasta %>% filter(key %in% bad_keys$key.x)%>%  select(chr, catalog_start_coordinate_0_based, catalog_end_coordinate)

#write.table(bad_call_loci, file = "Rosenberg_bad_loci_STR_catalog_coordinates.bed", sep = "\t", row.names = FALSE, quote = FALSE)

```

```{r}
#HipSTR loci with different pos and start values 
read.csv("~/Downloads/str_410_sgdp_loci_data-frames_410_sgdp_loci_hipstr (1).csv")%>% separate(h_gb, c("h_gb_1", "h_gb_2"), sep = "\\|") %>% mutate(h_gb_1 = as.numeric(h_gb_1), h_gb_2 = as.numeric(h_gb_2)) %>% mutate(h_allele_1 = (nchar(h_ref)+h_gb_1)/h_period, h_allele_2 = (nchar(h_ref)+h_gb_2)/h_period, h_alleles = floor(h_allele_1) + floor(h_allele_2), h_gbs = h_gb_1 + h_gb_2) %>% rename("key"= h_id,"hgdp_sample_id"= sample_id) %>% rename("end" = h_end, "chr" = h_chr) %>% filter(h_pos != h_start) %>% distinct(key)
```





