[get_sv_proximal_peaks]
pseudobulk_dir = 'gs://cpg-bioheart-test/str/atac-seq'
sv_vcf_path = ''  # TODO path to the SV VCF (bgzipped)
window_size = 1000000

# start with one cell type, then swap in the full list of 26 below
cell_types = 'ASDC'
# cell_types = 'ASDC,B_intermediate,B_memory,B_naive,CD14_Mono,CD16_Mono,CD4_CTL,CD4_Naive,CD4_Proliferating,CD4_TCM,CD4_TEM,CD8_Naive,CD8_TCM,CD8_TEM,HSPC,MAIT,NK,NK_CD56bright,NK_Proliferating,Plasmablast,Treg,cDC1,cDC2,dnT,gdT,pDC'

extract_job_storage = '20G'
job_cpu = 2
job_memory = 'standard'
job_storage = '0G'
