[get_cis_numpy]
input_methyl_dir = 'gs://cpg-bioheart-test/tenk10k/str/pacbio-methylation/combined_bed/filtered_set_5kb'
covariate_path = 'gs://cpg-bioheart-test/tenk10k/str/associatr/final-freeze/input_files/bioheart_n975_sample_covariates.csv'
chromosomes = 'chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22'
job_cpu = 0.25
job_memory = 'standard'
job_storage = '0G'
# To avoid exceeding Google Cloud quotas, set a concurrency as a limit.
max_parallel_jobs = 500
