---
title: "trf_input_creator"
author: "Hope"
date: "15/02/2023"
output: html_document
---

```{r}
library(readxl)
library(stringr)
```

```{r}
fasta = read_excel("482_loci_with_primers_UCSC_remove_fix_alt.xlsx") %>% select(-...1)
fasta$coordinate = gsub("\r\n", " ", fasta$coordinate)
fasta$coordinate = str_trim(fasta$coordinate, side = "both")
fasta = fasta %>% filter(coordinate != "no match")%>% separate(coordinate, c("coordinates", "PCR_length", "forward_primer", "reverse_primer", "PCR_sequence_1", "PCR_sequence_2", "PCR_sequence_3", "PCR_sequence_4", "PCR_sequence_5", "PCR_sequence_6", "PCR_sequence_7", "PCR_sequence_8"), sep = " ")

fasta = fasta %>% mutate(PCR_sequence_2 = replace_na(PCR_sequence_2, ""),
                  PCR_sequence_3 = replace_na(PCR_sequence_3, ""),
                  PCR_sequence_4 = replace_na(PCR_sequence_4, ""),
                  PCR_sequence_5 = replace_na(PCR_sequence_5, ""),
                  PCR_sequence_6 = replace_na(PCR_sequence_6, ""),
                  PCR_sequence_7 = replace_na(PCR_sequence_7, ""),
                  PCR_sequence_8 = replace_na(PCR_sequence_8, "")
  
)

fasta$PCR_sequence = paste(fasta$PCR_sequence_1, fasta$PCR_sequence_2, fasta$PCR_sequence_3, fasta$PCR_sequence_4, fasta$PCR_sequence_5, fasta$PCR_sequence_6, fasta$PCR_sequence_7, fasta$PCR_sequence_8)

fasta$PCR_sequence = gsub(" ", "", fasta$PCR_sequence)

fasta = fasta %>% select(-PCR_sequence_1, -PCR_sequence_2, - PCR_sequence_3, -PCR_sequence_4, -PCR_sequence_5, -PCR_sequence_6, -PCR_sequence_7, -PCR_sequence_8, -forward_primer, -reverse_primer)

fasta$PCR_length = gsub("bp", "", fasta$PCR_length)

fasta$coordinates_name = paste(fasta$coordinates, fasta$alternateName, sep = "_")

fasta_output = fasta %>% select(coordinates_name, PCR_sequence)

write.table(fasta_output, file = "trf_input.txt", sep = "\n", row.names = FALSE, quote = FALSE)
```

