[associatr]
celltypes='CD14_Mono'
chromosomes='chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr22'
#chromosomes = 'chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr21'
# gs://... to the chr-specific output of qc_filters_associatr.py
vcf_file_path='gs://cpg-bioheart-test/tenk10k/str/associatr/final_freeze/trans_pilot/top100nonhomopolymers/filtered_cd14_mono_variants.vcf'
pheno_cov_numpy_dir='gs://cpg-bioheart-test/tenk10k/str/associatr/final_freeze/input_files/bioheart_n975/pheno_cov_numpy/v1'
gene_list_dir ='gs://cpg-bioheart-test/tenk10k/str/associatr/final_freeze/input_files/bioheart_n975/scRNA_gene_lists/1_min_pct_cells_expressed'
max_parallel_jobs=1000
# version of the output
version='v5e-80nonhomopolymers'
# job storage
job_storage = '0G'
job_cpu =0.25
always_run=false
