[associatr]
celltypes='CD4_TCM'
chromosomes='chr22'
# gs://... to the chr-specific output of qc_filters_associatr.py
vcf_file_path='gs://cpg-bioheart-test/tenk10k/str/associatr/final_freeze/trans_pilot/filtered_cd4tcm_fm_variants.vcf'
pheno_cov_numpy_dir='gs://cpg-bioheart-test/tenk10k/str/associatr/final_freeze/input_files/tob_n950/pheno_cov_numpy/v1'
gene_list_dir ='gs://cpg-bioheart-test/tenk10k/str/associatr/final_freeze/input_files/tob_n950/scRNA_gene_lists/1_min_pct_cells_expressed'
max_parallel_jobs=500
# version of the output
version='v1-fm'
# job storage
job_storage = '0G'
job_cpu =0.25
always_run=false
