print(
            ','.join(
                [   
                    'sample_id',
                    'chr',
                    'start',
                    'e_qual',
                    'end',
                    'repeat_units_in_ref',
                    'ref_sequence_length',
                    'motif',
                    'e_GT',
                    'e_SO',
                    'e_allele_1',
                    'e_alelle_2',
                    'e_REPCI',
                    'e_ADSP',
                    'e_ADFL',
                    'e_ADIR',
                    'e_LC'
                ]
            )
            +'\n'
        )

